# Generated by Django 4.2.1 on 2024-03-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='transaction_id',
        ),
    ]
